apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sweb-pv-claim
  labels:
    app: sweb-pv-claim
    tier: database
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 64Gi
